EvalConf:
  multi_object: True
  max_steps: 500
  max_explore_steps: 2000000
  max_dist: 1.0
  is_gibson: False
  object_nav_path: "datasets/langmon/eval/test_mini"
  num_seq: 3
  scene_path: "datasets/scene_datasets/fphab/"
  results_path: "results_mlsfm_lseg/"
  log_rerun: False
  save_video: False
  save_maps: False
  use_pointnav: False
  square_im: True
  goal_query_type: "detailed" # "coarse", "fine", "detailed"
  goal_query_processing: "vanilla" #"extract_and_split_support"
  use_model: "lseg"

config: [
  ../mon/controller_habitat.yaml, # Default Habitat Controller
  ../mon/mapping_conf_sim.yaml,       # Default Mapping Configuration
  ../mon/planning_conf.yaml       # Default Planning Configuration
]

MappingConf:
  layered: False
