EvalConf:
  multi_object: True
  max_steps: 500
  max_explore_steps: 100
  max_dist: 1.5
  is_gibson: False
  object_nav_path: "datasets/langmon/eval/langnav/langnav/test"
  num_seq: 3
  scene_path: "datasets/scene_datasets/fphab/"
  results_path: "results_mlfm_relation_graph_spatial/"
  log_rerun: True
  save_video: False
  save_maps: False
  use_pointnav: False
  square_im: True
  goal_query_type: "detailed" # "coarse", "fine", "detailed"
  goal_query_processing: "extract_graph" #"extract_and_split_support" #"extract"

config: [
  ../mon/controller_habitat.yaml, # Default Habitat Controller
  ../mon/mapping_conf_sim.yaml,       # Default Mapping Configuration
  ../mon/planning_conf.yaml       # Default Planning Configuration
]

MappingConf:
  layered: True
  z_bins_lower: -1.0
  z_bins_upper: 1.0
  z_bins_step: 0.8
  store_raw_images: False
  use_gpt: True

PlanningConf:
  fuse_similarity: "object_relation" #"layerwisemax"
