EvalConf:
  multi_object: True
  max_steps: 1500
  max_dist: 1.5
  is_gibson: False
  object_nav_path: "datasets/langmon/langmon/fphab/v0.2/minival_1on"
  scene_path: "datasets/scene_datasets/fphab/"
  results_path: "results_langmon_1on_split_find_go/"
  log_rerun: False
  use_pointnav: False
  square_im: True
  goal_query_type: "detailed" # "coarse", "fine", "detailed"
  goal_query_processing: "extract"

config: [
  ./controller_habitat.yaml, # Default Habitat Controller
  ./mapping_conf_sim.yaml,       # Default Mapping Configuration
  ./planning_conf.yaml       # Default Planning Configuration
]